-- DATABASE CREATION
CREATE DATABASE DistribuidoraDB;


-- TABLES CREATIONS

-- TABLE CATEGORIES
CREATE TABLE TB_CATEGORIES(
	CATEGORY_ID INT IDENTITY,
	CATEGORY_NAME VARCHAR(80) NOT NULL,

	CONSTRAINT PK_TB_CATEGORIAS PRIMARY KEY(CATEGORY_ID)
);


-- TABLE PRODUCTS
CREATE TABLE TB_PRODUCTS(
	PRODUCT_ID INT IDENTITY,
	PRODUCT_NAME VARCHAR(80) NOT NULL,
	PRODUCT_CATEGORY_ID INT NOT NULL,
	PRODUCT_PRICE DECIMAL(18,2) NOT NULL,
	PRODUCT_STOCK INT,
	PRODUCT_ACTIVE BIT,
	PRODUCT_REGISTRATION_DATE DATE NOT NULL,
	PRODUCT_DATE_UPDATE DATE,

	-- PRIMARY KEY
	CONSTRAINT PK_TB_PRODUCTS PRIMARY KEY(PRODUCT_ID),

	-- FOREIGN KEY
	CONSTRAINT FK_PRODUCTS_CATEGORIES
		FOREIGN KEY(PRODUCT_CATEGORY_ID)
		REFERENCES TB_CATEGORIES(CATEGORY_ID)
);


-- TABLE CUSTOMERS
CREATE TABLE TB_CUSTOMERS(
	CUSTOMER_ID INT IDENTITY,
	CUSTOMER_NAME VARCHAR(120) NOT NULL,
	CUSTOMER_EMAIL VARCHAR(120) NOT NULL,
	CUSTOMER_CITY VARCHAR(80) NOT NULL,
	CUSTOMER_STATE VARCHAR(80) NOT NULL,
	CUSTOMER_REGISTRATION_DATE DATE NOT NULL,
	CUSTOMER_UPDATE_DATE DATE NOT NULL,

	-- PK
	CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY(CUSTOMER_ID)
);

-- CREATE UNIQUE INDEX ON CUSTOMERS
CREATE UNIQUE INDEX IX_TB_CUSTOMERS_EMAIL
ON TB_CUSTOMERS(CUSTOMER_EMAIL);


-- TABLE SELLERS
CREATE TABLE TB_SELLERS(
	SELLER_ID INT IDENTITY,
	SELLER_NAME VARCHAR(120) NOT NULL,
	SELLER_PERCENT_COMISSION DECIMAL(3,2)

	-- PK
	CONSTRAINT PK_SELLER_ID PRIMARY KEY (SELLER_ID)
);


-- TABLE STATUS
CREATE TABLE TB_STATUS(
	STATUS_ID INT IDENTITY,
	STATUS_DESCRIPTION VARCHAR(50) NOT NULL,

	-- PK
	CONSTRAINT PK_STATUS_ID PRIMARY KEY(STATUS_ID)
);

-- TABLE ORDERS
CREATE TABLE TB_ORDERS(
	ORDER_ID INT IDENTITY,
	ORDER_CUSTOMER_ID INT,
	ORDER_SELLER_ID INT NOT NULL,
	ORDER_STATUS_ID INT NOT NULL,
	ORDER_CREATION_DATE DATE NOT NULL,
	ORDER_UPDATE_DATE DATE,

	-- PK
	CONSTRAINT PK_ORDER_ID PRIMARY KEY(ORDER_ID),

	-- FK
	CONSTRAINT FK_ORDER_CUSTOMER_ID
		FOREIGN KEY(ORDER_CUSTOMER_ID)
		REFERENCES TB_CUSTOMERS(CUSTOMER_ID),

	CONSTRAINT FK_ORDER_SELLER_ID
		FOREIGN KEY (ORDER_SELLER_ID)
		REFERENCES TB_SELLERS(SELLER_ID),

	CONSTRAINT FK_ODER_STATUS_ID
		FOREIGN KEY (ORDER_STATUS_ID)
		REFERENCES TB_STATUS(STATUS_ID)
);


-- TABLE ORDER ITENS
CREATE TABLE TB_ORDER_ITENS(
	ORDER_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	ORDER_ITEM_QUANTIDADE INT NOT NULL,
	ORDER_ITEM_UNIT_VALUE DECIMAL(18,2) NOT NULL,

	-- PK 
	CONSTRAINT PK_ORDER_ITEM PRIMARY KEY(ORDER_ID, PRODUCT_ID),

	--FK
	CONSTRAINT FK_ORDER_ITEM_ORDER_ID
		FOREIGN KEY (ORDER_ID)
		REFERENCES TB_ORDERS(ORDER_ID),

	CONSTRAINT FK_ORDER_ITEM_PRODUCT_ID
		FOREIGN KEY (PRODUCT_ID)
		REFERENCES TB_PRODUCTS(PRODUCT_ID)
);

